  {db-container-name}:
    image: {db-image}
    container_name: {db-container-name}
    hostname: {db-container-name}
    environment:
        POSTGRES_USER: {postgres-user}
        POSTGRES_PASSWORD: {postgres-pass}
        PGDATA: /var/lib/postgresql/data
    ports:
        - "{postgres-port-external}:{postgres-port-internal}"
    restart: always
    volumes:
        - {db-volume-name}:/var/lib/postgresql/data
    networks:
      - {network}
