# Generated by Django 3.1.2 on 2022-04-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='file_name_original',
            field=models.TextField(blank=True, null=True),
        ),
    ]
